AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for postgres lab'

Parameters:
  User:
    Type: String
    Description: Username for resource naming and tags

  PublicIP:
    Type: String
    Description: Public IP address for SSH access

  InstanceType:
    Type: String
    Default: m6i.2xlarge

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs

  UbuntuAmiId:
    Type: AWS::EC2::Image::Id
    Description: Ubuntu AMI ID

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${User}-postgres-lab
      GroupDescription: Security group for accessing postgres lab machines
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub ${PublicIP}/32
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${User}-postgres-lab
        - Key: contact
          Value: !Ref User

  PostgresIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${User}-postgres-s3-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::davidreaver-postgres-lab
                  - arn:aws:s3:::davidreaver-postgres-lab/*
      Tags:
        - Key: contact
          Value: !Ref User

  PostgresInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref PostgresIAMRole

  PostgresLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${User}-postgres-launch-template
      LaunchTemplateData:
        ImageId: !Ref UbuntuAmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref User
        SecurityGroupIds:
          - !Ref SecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt PostgresInstanceProfile.Arn
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100
              VolumeType: gp3
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${User}-postgres
              - Key: contact
                Value: !Ref User
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub ${User}-postgres
              - Key: contact
                Value: !Ref User
        UserData:
          Fn::Base64:
            !Sub |
              #!/usr/bin/env bash

              set -euo pipefail

              export PGLAB_USER=${User}

              # Install awscli
              apt-get update
              apt-get install -y unzip curl
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
              rm -rf aws awscliv2.zip
              aws --version

              # Download and run instance-specific scripts
              aws s3 cp s3://davidreaver-postgres-lab/common-setup.sh /tmp/
              chmod +x /tmp/common-setup.sh
              /tmp/common-setup.sh

              aws s3 cp s3://davidreaver-postgres-lab/postgres-setup.sh /tmp/
              chmod +x /tmp/postgres-setup.sh
              /tmp/postgres-setup.sh

  PostgresASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${User}-postgres-asg
      VPCZoneIdentifier: !Ref SubnetIds
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 10
      LaunchTemplate:
        LaunchTemplateId: !Ref PostgresLaunchTemplate
        Version: !GetAtt PostgresLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: !Sub ${User}-postgres
          PropagateAtLaunch: true
        - Key: contact
          Value: !Ref User
          PropagateAtLaunch: true

Outputs:
  SecurityGroupId:
    Description: ID of the Security Group
    Value: !Ref SecurityGroup
  PostgresAutoScalingGroupName:
    Description: Name of the postgres Auto Scaling Group
    Value: !Ref PostgresASG
  PostgresIAMRoleArn:
    Description: ARN of the IAM Role
    Value: !GetAtt PostgresIAMRole.Arn
